// <auto-generated />
using Corpus.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CorpusApi.Migrations
{
    [DbContext(typeof(CorpusContext))]
    partial class CorpusContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Corpus.Models.Summary", b =>
                {
                    b.Property<int>("SummaryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserSumm");

                    b.HasKey("SummaryId");

                    b.ToTable("Corpus");

                    b.HasData(
                        new
                        {
                            SummaryId = 1,
                            UserSumm = "This will be the summary of the video they see. It will be a somewhat lengthy summary, but hopefully not too verbose."
                        },
                        new
                        {
                            SummaryId = 2,
                            UserSumm = "This is another summary for testing purposes..."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
